// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFcnn8D1HfeIwQeRMvY9qSksEt2vouYw',
    appId: '1:1077137180752:web:4dc808a07c65dd240b6955',
    messagingSenderId: '1077137180752',
    projectId: 'fir-authentication-cf69b',
    authDomain: 'fir-authentication-cf69b.firebaseapp.com',
    storageBucket: 'fir-authentication-cf69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2hAKK89MRqGk5h4paN_ScLiMJuYD5sg',
    appId: '1:1077137180752:android:4512a78e2166328b0b6955',
    messagingSenderId: '1077137180752',
    projectId: 'fir-authentication-cf69b',
    storageBucket: 'fir-authentication-cf69b.appspot.com',
  );
}
